FROM node:hydrogen-alpine

# Install dependencies
RUN mkdir /app && chown node:node /app
WORKDIR /app
USER node
COPY --chown=node:node ./server/package.json ./server/package-lock.json ./
RUN npm install

RUN mkdir /app/server
WORKDIR /app/server

# Start application with live reload
CMD sh -c "npm run dev"